package cn.kk.kkdict.types;

public enum Language {
    AA("aa"),
    AB("ab"),
    AF("af"),
    AK("ak"),
    ALS("als"),
    AM("am"),
    AN("an"),
    ANG("ang"),
    AR("ar"),
    ARC("arc"),
    AS("as"),
    AST("ast"),
    AV("av"),
    AY("ay"),
    AZ("az"),
    BA("ba"),
    BAR("bar"),
    BAT_SMG("bat-smg"),
    BCL("bcl"),
    BE("be"),
    BE_X_OLD("be-x-old"),
    BG("bg"),
    BH("bh"),
    BI("bi"),
    BM("bm"),
    BN("bn"),
    BO("bo"),
    BPY("bpy"),
    BR("br"),
    BS("bs"),
    BUG("bug"),
    BXR("bxr"),
    CA("ca"),
    CBK_ZAM("cbk-zam"),
    CDO("cdo"),
    CE("ce"),
    CEB("ceb"),
    CH("ch"),
    CHR("chr"),
    CHY("chy"),
    CO("co"),
    CR("cr"),
    CRH("crh"),
    CS("cs"),
    CSB("csb"),
    CU("cu"),
    CV("cv"),
    CY("cy"),
    DA("da"),
    DE("de"),
    DIQ("diq"),
    DSB("dsb"),
    DV("dv"),
    DZ("dz"),
    EE("ee"),
    EL("el"),
    EML("eml"),
    EN("en"),
    EO("eo"),
    ES("es"),
    ET("et"),
    EU("eu"),
    EXT("ext"),
    FA("fa"),
    FF("ff"),
    FI("fi"),
    FIU_VRO("fiu-vro"),
    FJ("fj"),
    FO("fo"),
    FR("fr"),
    FRP("frp"),
    FUR("fur"),
    FY("fy"),
    GA("ga"),
    GAN("gan"),
    GD("gd"),
    GL("gl"),
    GLK("glk"),
    GN("gn"),
    GOT("got"),
    GU("gu"),
    GV("gv"),
    HA("ha"),
    HAK("hak"),
    HAW("haw"),
    HE("he"),
    HI("hi"),
    HIF("hif"),
    HR("hr"),
    HSB("hsb"),
    HT("ht"),
    HU("hu"),
    HY("hy"),
    IA("ia"),
    ID("id"),
    IE("ie"),
    IG("ig"),
    IK("ik"),
    ILO("ilo"),
    IO("io"),
    IS("is"),
    IT("it"),
    IU("iu"),
    JA("ja"),
    JBO("jbo"),
    JV("jv"),
    KA("ka"),
    KAA("kaa"),
    KAB("kab"),
    KG("kg"),
    KI("ki"),
    KK("kk"),
    KL("kl"),
    KM("km"),
    KN("kn"),
    KO("ko"),
    KS("ks"),
    KSH("ksh"),
    KU("ku"),
    KV("kv"),
    KW("kw"),
    KY("ky"),
    LA("la"),
    LAD("lad"),
    LB("lb"),
    LBE("lbe"),
    LG("lg"),
    LI("li"),
    LIJ("lij"),
    LMO("lmo"),
    LN("ln"),
    LO("lo"),
    LT("lt"),
    LV("lv"),
    MAP_BMS("map-bms"),
    MDF("mdf"),
    MG("mg"),
    MH("mh"),
    MI("mi"),
    MK("mk"),
    ML("ml"),
    MN("mn"),
    MR("mr"),
    MS("ms"),
    MT("mt"),
    MY("my"),
    MYV("myv"),
    MZN("mzn"),
    NA("na"),
    NAH("nah"),
    NAP("nap"),
    NDS("nds"),
    NDS_NL("nds-nl"),
    NE("ne"),
    NEW("new"),
    NG("ng"),
    NL("nl"),
    NN("nn"),
    NO("no"),
    NOV("nov"),
    NRM("nrm"),
    NV("nv"),
    NY("ny"),
    OC("oc"),
    OM("om"),
    OR("or"),
    OS("os"),
    PA("pa"),
    PAG("pag"),
    PAM("pam"),
    PAP("pap"),
    PDC("pdc"),
    PI("pi"),
    PIH("pih"),
    PL("pl"),
    PMS("pms"),
    PS("ps"),
    PT("pt"),
    QU("qu"),
    RM("rm"),
    RMY("rmy"),
    RN("rn"),
    RO("ro"),
    ROA_RUP("roa-rup"),
    ROA_TARA("roa-tara"),
    RU("ru"),
    RW("rw"),
    SA("sa"),
    SAH("sah"),
    SC("sc"),
    SCN("scn"),
    SCO("sco"),
    SD("sd"),
    SE("se"),
    SG("sg"),
    SH("sh"),
    SI("si"),
    SIMPLE("simple"),
    SK("sk"),
    SL("sl"),
    SM("sm"),
    SN("sn"),
    SO("so"),
    SQ("sq"),
    SR("sr"),
    SRN("srn"),
    SS("ss"),
    ST("st"),
    STQ("stq"),
    SU("su"),
    SV("sv"),
    SW("sw"),
    SZL("szl"),
    TA("ta"),
    TE("te"),
    TET("tet"),
    TG("tg"),
    TH("th"),
    TI("ti"),
    TK("tk"),
    TL("tl"),
    TN("tn"),
    TO("to"),
    TPI("tpi"),
    TR("tr"),
    TS("ts"),
    TT("tt"),
    TUM("tum"),
    TW("tw"),
    TY("ty"),
    UDM("udm"),
    UG("ug"),
    UK("uk"),
    UR("ur"),
    UZ("uz"),
    VE("ve"),
    VEC("vec"),
    VI("vi"),
    VLS("vls"),
    VO("vo"),
    WA("wa"),
    WAR("war"),
    WO("wo"),
    WUU("wuu"),
    XAL("xal"),
    XH("xh"),
    YI("yi"),
    YO("yo"),
    ZA("za"),
    ZEA("zea"),
    ZH("zh"),
    ZH_CLASSICAL("zh-classical"),
    ZH_MIN_NAN("zh-min-nan"),
    ZH_YUE("zh-yue"),
    ZU("zu"),
    MO("mo"),
    PNB("pnb"), ;

    public static final String TYPE_ID = "语";
    public final String key;

    Language(final String key) {
        this.key = key;
    }

    private static final String[][] LNGS_ZH = { { AA.key, "阿法尔语" }, { AA.key, "阿法语" }, { AB.key, "阿布哈西亚语‎" },
            { AB.key, "阿布哈兹语" }, { AF.key, "阿非利堪斯语" }, { AF.key, "南非荷兰语" }, { AF.key, "南非语" }, { AK.key, "阿坎语" },
            { ALS.key, "阿勒曼尼语" }, { ALS.key, "瑞士德语" }, { AM.key, "阿姆哈拉语" }, { AN.key, "阿拉贡语" }, { AN.key, "亚拉冈语" },
            { ANG.key, "古英语" }, { AR.key, "阿拉伯语" }, { ARC.key, "阿拉米语" }, { AS.key, "阿萨姆语" }, { AST.key, "阿斯图里亚斯语" },
            { AV.key, "阿瓦尔语" }, { AY.key, "艾马拉语" }, { AZ.key, "阿塞拜疆语" }, { AZ.key, "阿塞拜疆语" }, { BA.key, "巴什基尔语" },
            { BA.key, "巴什噶尔语" }, { BAR.key, "奥地利-巴伐利亚语" }, { BAT_SMG.key, "萨莫吉希亚语" }, { BCL.key, "中比科尔语" },
            { BE.key, "白俄罗斯语" }, { BE_X_OLD.key, "白俄罗斯语（1933年前）" }, { BG.key, "保加利亚语" }, { BH.key, "比哈尔语" },
            { BI.key, "比斯拉玛语" }, { BM.key, "班巴拉语" }, { BN.key, "孟加拉语" }, { BO.key, "藏语" },
            { BPY.key, "比什奴普莱利亚-曼尼浦尔语" }, { BR.key, "布列塔尼语" }, { BR.key, "布里多尼语" }, { BS.key, "波斯尼亚语" },
            { BS.key, "波斯尼亚语" }, { BUG.key, "布吉语" }, { BXR.key, "布里亚特语" }, { CA.key, "加泰隆尼亚语" }, { CA.key, "加泰罗尼亚语" },
            { CA.key, "加泰隆语" }, { CA.key, "瓦伦西亚语" }, { CBK_ZAM.key, "三宝颜共同语" }, { CDO.key, "闽东话" }, { CE.key, "车臣语" },
            { CEB.key, "宿务语" }, { CEB.key, "宿雾语" }, { CH.key, "查莫罗语" }, { CHR.key, "切罗基语" }, { CHY.key, "夏延语" },
            { CO.key, "科西嘉语" }, { CR.key, "克里语" }, { CRH.key, "克里米亚鞑靼语" }, { CS.key, "捷克语" }, { CSB.key, "卡舒比语" },
            { CU.key, "古教会斯拉夫语" }, { CV.key, "楚瓦什语" }, { CY.key, "威尔士语" }, { CY.key, "威尔斯语" }, { DA.key, "丹麦语" },
            { DE.key, "德语" }, { DIQ.key, "南扎扎其语" }, { DSB.key, "下索布语" }, { DV.key, "迪维希语" }, { DZ.key, "宗喀语" },
            { DZ.key, "不丹语" }, { EE.key, "埃维语" }, { EE.key, "幽语" }, { EL.key, "现代希腊语" }, { EML.key, "艾米利亚-罗马涅语" },
            { EN.key, "英语" }, { EO.key, "世界语" }, { ES.key, "西班牙语" }, { ET.key, "爱沙尼亚语" }, { EU.key, "巴斯克语" },
            { EXT.key, "埃斯特雷马杜拉语" }, { FA.key, "波斯语" }, { FF.key, "富拉语" }, { FF.key, "弗拉尼语" }, { FI.key, "芬兰语" },
            { FIU_VRO.key, "佛罗语" }, { FJ.key, "斐济语" }, { FO.key, "法罗斯语" }, { FO.key, "法罗语" }, { FR.key, "法语" },
            { FRP.key, "法兰克-普罗旺斯语" }, { FUR.key, "弗留利语" }, { FY.key, "弗里西亚语" }, { FY.key, "西弗里西亚语" },
            { GA.key, "爱尔兰语" }, { GAN.key, "赣语" }, { GD.key, "苏格兰盖尔语" }, { GL.key, "加利西亚语" }, { GL.key, "加里西亚语" },
            { GLK.key, "吉拉克语" }, { GN.key, "瓜拉尼语" }, { GOT.key, "哥特语" }, { GOT.key, "哥德语" }, { GU.key, "古吉拉特语" },
            { GV.key, "马恩岛语" }, { GV.key, "曼岛语" }, { HA.key, "豪萨语" }, { HA.key, "豪撒语" }, { HAK.key, "客家话" },
            { HAW.key, "夏威夷语" }, { HE.key, "希伯来语" }, { HI.key, "印地语" }, { HIF.key, "斐济印度斯坦语" }, { HR.key, "克罗地亚语" },
            { HR.key, "克罗地亚语" }, { HSB.key, "上索布语" }, { HT.key, "海地克里奥尔语" }, { HU.key, "匈牙利语" }, { HY.key, "亚美尼亚语" },
            { IA.key, "国际语（国际语A）" }, { ID.key, "印尼语" }, { ID.key, "印度尼西亚语" }, { IE.key, "西方国际语（国际语E）" },
            { IG.key, "伊博语" }, { IG.key, "伊格柏语" }, { IK.key, "依努庇克语" }, { IK.key, "伊努必语" }, { ILO.key, "伊洛卡诺语" },
            { IO.key, "伊多语" }, { IS.key, "冰岛语" }, { IT.key, "意大利语" }, { IT.key, "意大利语" }, { IU.key, "伊努伊特语" },
            { IU.key, "伊努特语" }, { IU.key, "因纽特语" }, { JA.key, "日语" }, { JA.key, "日本语" }, { JBO.key, "逻辑语" },
            { JV.key, "爪哇语" }, { KA.key, "格鲁吉亚语" }, { KA.key, "乔治亚语" }, { KAA.key, "卡拉卡尔帕克语" }, { KAB.key, "卡布列语" },
            { KG.key, "刚果语" }, { KI.key, "基库尤语" }, { KI.key, "吉库尤语" }, { KK.key, "哈萨克语" }, { KL.key, "格陵兰语" },
            { KM.key, "高棉语" }, { KM.key, "中高棉语" }, { KN.key, "卡纳达语" }, { KN.key, "康纳达语" }, { KO.key, "朝鲜语" },
            { KO.key, "韩语" }, { KS.key, "克什米尔语" }, { KS.key, "喀什米尔语" }, { KSH.key, "库尔施语" }, { KU.key, "库尔德语" },
            { KU.key, "库德语" }, { KV.key, "科米语" }, { KW.key, "康沃尔语" }, { KW.key, "康瓦尔语" }, { KY.key, "吉尔吉斯语" },
            { KY.key, "柯尔克孜语" }, { LA.key, "拉丁语" }, { LAD.key, "拉迪诺语" }, { LB.key, "卢森堡语" }, { LBE.key, "腊克语" },
            { LG.key, "干达语" }, { LG.key, "卢干达语" }, { LI.key, "林堡语" }, { LIJ.key, "利古里亚语" }, { LMO.key, "伦巴底语" },
            { LN.key, "林加拉语" }, { LN.key, "林格拉语" }, { LO.key, "老挝语" }, { LO.key, "老挝语" }, { LT.key, "立陶宛语" },
            { LV.key, "拉脱维亚语" }, { MAP_BMS.key, "班尤马山语" }, { MDF.key, "莫克沙语" }, { MG.key, "马达加斯加语" },
            { MG.key, "马拉加西语" }, { MH.key, "马绍尔语" }, { MI.key, "毛利语" }, { MK.key, "马其顿语" }, { ML.key, "马拉雅拉姆语" },
            { MN.key, "蒙古语" }, { MR.key, "马拉地语" }, { MR.key, "马拉提语" }, { MS.key, "马来语" }, { MT.key, "马耳他语" },
            { MT.key, "马尔他语" }, { MY.key, "缅甸语" }, { MYV.key, "厄尔兹亚语" }, { MZN.key, "马赞德兰语" }, { NA.key, "瑙鲁语" },
            { NA.key, "诺鲁语" }, { NAH.key, "纳瓦特尔语" }, { NAP.key, "拿坡里语" }, { NDS.key, "低地撒克逊语" },
            { NDS_NL.key, "荷兰低地萨克逊语" }, { NE.key, "尼泊尔语" }, { NEW.key, "尼瓦尔语" }, { NG.key, "恩敦加语" },
            { NG.key, "恩东加语" }, { NL.key, "荷兰语" }, { NN.key, "新挪威语" }, { NO.key, "挪威语" }, { NOV.key, "诺维亚语" },
            { NRM.key, "诺曼语" }, { NV.key, "纳瓦霍语" }, { NV.key, "纳瓦荷语" }, { NY.key, "尼扬贾语" }, { NY.key, "齐切瓦语" },
            { OC.key, "奥克西唐语" }, { OC.key, "奥克西坦语" }, { OC.key, "奥克语" }, { OM.key, "奥罗莫语" }, { OR.key, "奥利亚语" },
            { OR.key, "奥里亚语" }, { OS.key, "奥塞梯语" }, { OS.key, "奥塞提语" }, { PA.key, "旁遮普语" }, { PAG.key, "邦阿西楠语" },
            { PAM.key, "邦板牙语" }, { PAP.key, "帕皮亚门托语" }, { PDC.key, "宾夕法尼亚德语" }, { PI.key, "巴利语" },
            { PIH.key, "皮特凯恩-诺福克语" }, { PL.key, "波兰语" }, { PMS.key, "皮埃蒙特语" }, { PS.key, "普什图语" }, { PS.key, "帕图语" },
            { PT.key, "葡萄牙语" }, { QU.key, "克丘亚语" }, { QU.key, "凯楚亚语" }, { QU.key, "奇楚瓦语" }, { RM.key, "罗曼什语" },
            { RMY.key, "Vlax 罗姆语" }, { RN.key, "基隆迪语" }, { RN.key, "克伦地语" }, { RO.key, "罗马尼亚语" },
            { ROA_RUP.key, "阿罗马尼亚语" }, { ROA_TARA.key, "塔兰托语" }, { RU.key, "俄语" }, { RW.key, "基尼阿万达语" },
            { RW.key, "卢旺达语" }, { SA.key, "梵语" }, { SAH.key, "雅库特语" }, { SC.key, "撒丁语" }, { SC.key, "萨丁尼亚语" },
            { SCN.key, "西西里语" }, { SCO.key, "苏格兰语" }, { SD.key, "信德语" }, { SD.key, "辛德语" }, { SE.key, "北萨米语" },
            { SE.key, "北萨莫斯语" }, { SG.key, "桑戈语" }, { SH.key, "塞尔维亚-克罗地亚语" }, { SI.key, "僧加罗语" }, { SI.key, "僧伽罗语" },
            { SIMPLE.key, "简单英语" }, { SK.key, "斯洛伐克语" }, { SL.key, "斯洛文尼亚语" }, { SL.key, "斯洛文尼亚语" },
            { SM.key, "萨摩亚语" }, { SN.key, "修纳语" }, { SN.key, "绍纳语" }, { SO.key, "索马里语" }, { SO.key, "索马里语" },
            { SQ.key, "阿尔巴尼亚语" }, { SR.key, "塞尔维亚语" }, { SRN.key, "苏里南汤加语" }, { SS.key, "斯瓦特语" }, { SS.key, "斯威士兰语" },
            { ST.key, "南塞索托语" }, { ST.key, "索托语" }, { ST.key, "南梭苏语" }, { STQ.key, "沙特弗里西语" }, { SU.key, "巽他语" },
            { SV.key, "瑞典语" }, { SW.key, "斯瓦希里语" }, { SW.key, "斯瓦西里语" }, { SZL.key, "西里西亚语" }, { TA.key, "泰米尔语" },
            { TA.key, "坦米尔语" }, { TA.key, "淡米尔语" }, { TE.key, "泰卢固语" }, { TET.key, "特塔姆语" }, { TET.key, "德顿语" },
            { TG.key, "塔吉克语" }, { TH.key, "泰语" }, { TI.key, "提格里尼亚语" }, { TI.key, "提格利尼亚语" }, { TK.key, "土库曼语" },
            { TL.key, "塔加洛语" }, { TL.key, "塔加拉语" }, { TL.key, "他加禄语" }, { TN.key, "茨瓦纳语" }, { TO.key, "汤加语 (汤加岛)" },
            { TO.key, "东加语" }, { TPI.key, "托克皮辛语" }, { TPI.key, "巴布亚皮钦语" }, { TR.key, "土耳其语" }, { TS.key, "聪加语" },
            { TS.key, "宗加语" }, { TS.key, "宋加语" }, { TT.key, "塔塔尔语" }, { TT.key, "鞑靼语" }, { TUM.key, "奇图姆布卡语" },
            { TW.key, "契维语" }, { TW.key, "特威语" }, { TW.key, "多威语" }, { TW.key, "奇族语" }, { TY.key, "塔希提语" },
            { TY.key, "大溪地语" }, { UDM.key, "乌德穆尔特语" }, { UG.key, "维吾尔语" }, { UK.key, "乌克兰语" }, { UR.key, "乌尔都语" },
            { UR.key, "乌都语" }, { UR.key, "晤鲁都语" }, { UZ.key, "乌兹别克语" }, { UZ.key, "乌孜别克语" }, { VE.key, "文达语" },
            { VE.key, "温达语" }, { VEC.key, "威尼斯语" }, { VI.key, "越南语" }, { VI.key, "京语" }, { VLS.key, "佛兰芒语" },
            { VO.key, "沃拉普克语" }, { WA.key, "瓦龙语" }, { WA.key, "华隆语" }, { WA.key, "瓦隆语" }, { WAR.key, "瓦赖语" },
            { WO.key, "沃洛夫语" }, { WO.key, "渥鲁夫语" }, { WUU.key, "吴语" }, { XAL.key, "卡尔梅克语" }, { XAL.key, "卫拉特语" },
            { XH.key, "科萨语" }, { YI.key, "依地语" }, { YI.key, "意第绪语" }, { YO.key, "约鲁巴语" }, { ZA.key, "壮语" },
            { ZEA.key, "西兰语" }, { ZH.key, "中文" }, { ZH.key, "汉语" }, { ZH_CLASSICAL.key, "文言文" },
            { ZH_MIN_NAN.key, "闽南话" }, { ZH_YUE.key, "粤语" }, { ZU.key, "祖鲁语" }, };

    public static final String[] LANGUAGES_ZH_ISO = new String[LNGS_ZH.length];
    public static final String[] LANGUAGES_ZH = new String[LNGS_ZH.length];
    static {
        int i = 0;
        for (String[] lng : LNGS_ZH) {
            LANGUAGES_ZH_ISO[i] = lng[0];
            LANGUAGES_ZH[i] = lng[1];
            i++;
        }
    }

    private static final String[][] LNGS_EN = { { AA.key, "Afar" }, { AB.key, "Abkhazian" }, { AF.key, "Afrikaans" },
            { AK.key, "Akan" }, { ALS.key, "Alemannic German" }, { ALS.key, "Swiss German" }, { AM.key, "Amharic" },
            { AN.key, "Aragonese" }, { ANG.key, "Old English" }, { ANG.key, "Anglo-Saxon" }, { AR.key, "Arabic" },
            { ARC.key, "Aramaic" }, { AS.key, "Assamese" }, { AST.key, "Asturian" }, { AV.key, "Avaric" },
            { AY.key, "Aymara" }, { AZ.key, "Azerbaijani" }, { BA.key, "Bashkir" }, { BAR.key, "Bavarian" },
            { BAT_SMG.key, "Samogitian" }, { BCL.key, "Central Bicolano" }, { BE.key, "Belarusian" },
            { BE_X_OLD.key, "Belarusian (taraškevica)" }, { BG.key, "Bulgarian" }, { BH.key, "Bihari" },
            { BI.key, "Bislama" }, { BM.key, "Bambara" }, { BN.key, "Bengali" }, { BO.key, "Tibetan" },
            { BPY.key, "Bishnupriya" }, { BR.key, "Breton" }, { BS.key, "Bosnian" }, { BUG.key, "Buginese" },
            { BXR.key, "Buriat" }, { CA.key, "Catalan" }, { CBK_ZAM.key, "Zamboangueño Chavacano" },
            { CDO.key, "Min Dong" }, { CE.key, "Chechen" }, { CEB.key, "Cebuano" }, { CH.key, "Chamorro" },
            { CHR.key, "Cherokee" }, { CHY.key, "Cheyenne" }, { CO.key, "Corsican" }, { CR.key, "Cree" },
            { CRH.key, "Crimean Tatar" }, { CS.key, "Czech" }, { CSB.key, "Kashubian" }, { CU.key, "Church Slavic" },
            { CV.key, "Chuvash" }, { CY.key, "Welsh" }, { DA.key, "Danish" }, { DE.key, "German" },
            { DIQ.key, "Dimli" }, { DSB.key, "Lower Sorbian" }, { DV.key, "Dhivehi" }, { DV.key, "Divehi" },
            { DZ.key, "Dzongkha" }, { EE.key, "Ewe" }, { EL.key, "Modern Greek" }, { EML.key, "Emiliano-Romagnolo" },
            { EN.key, "English" }, { EO.key, "Esperanto" }, { ES.key, "Spanish" }, { ET.key, "Estonian" },
            { EU.key, "Basque" }, { EXT.key, "Extremaduran" }, { FA.key, "Persian" }, { FF.key, "Fulah" },
            { FI.key, "Finnish" }, { FIU_VRO.key, "Võro" }, { FJ.key, "Fijian" }, { FO.key, "Faroese" },
            { FR.key, "French" }, { FRP.key, "Franco-Provençal" }, { FUR.key, "Friulian" },
            { FY.key, "Western Frisian" }, { FY.key, "West Frisian" }, { GA.key, "Irish" }, { GAN.key, "Gan" },
            { GD.key, "Scottish Gaelic" }, { GL.key, "Galician" }, { GLK.key, "Gilaki" }, { GN.key, "Guarani" },
            { GOT.key, "Gothic" }, { GU.key, "Gujarati" }, { GV.key, "Manx" }, { HA.key, "Hausa" },
            { HAK.key, "Hakka" }, { HAW.key, "Hawaiian" }, { HE.key, "Hebrew" }, { HI.key, "Hindi" },
            { HIF.key, "Fijian Hindustani" }, { HR.key, "Croatian" }, { HSB.key, "Upper Sorbian" },
            { HT.key, "Haitian" }, { HU.key, "Hungarian" }, { HY.key, "Armenian" }, { IA.key, "Interlingua (IALA)" },
            { ID.key, "Indonesian" }, { IE.key, "Interlingue" }, { IG.key, "Igbo" }, { IK.key, "Inupiaq" },
            { IK.key, "Inupiak" }, { ILO.key, "Iloko" }, { IO.key, "Ido" }, { IS.key, "Icelandic" },
            { IT.key, "Italian" }, { IU.key, "Inuktitut" }, { JA.key, "Japanese" }, { JBO.key, "Lojban" },
            { JV.key, "Javanese" }, { KA.key, "Georgian" }, { KAA.key, "Kara-Kalpak" }, { KAB.key, "Kabyle" },
            { KG.key, "Kongo" }, { KI.key, "Kikuyu" }, { KK.key, "Kazakh" }, { KL.key, "Kalaallisut" },
            { KL.key, "Greenlandic" }, { KM.key, "Central Khmer" }, { KM.key, "Cambodian" }, { KN.key, "Kannada" },
            { KO.key, "Korean" }, { KS.key, "Kashmiri" }, { KSH.key, "Kölsch" }, { KU.key, "Kurdish" },
            { KV.key, "Komi" }, { KW.key, "Cornish" }, { KY.key, "Kirghiz" }, { LA.key, "Latin" },
            { LAD.key, "Ladino" }, { LB.key, "Luxembourgish" }, { LBE.key, "Lak" }, { LG.key, "Ganda" },
            { LI.key, "Limburgan" }, { LI.key, "Limburgian" }, { LIJ.key, "Ligurian" }, { LMO.key, "Lombard" },
            { LN.key, "Lingala" }, { LO.key, "Lao" }, { LT.key, "Lithuanian" }, { LV.key, "Latvian" },
            { MAP_BMS.key, "Banyumasan" }, { MDF.key, "Moksha" }, { MG.key, "Malagasy" }, { MH.key, "Marshallese" },
            { MI.key, "Maori" }, { MK.key, "Macedonian" }, { ML.key, "Malayalam" }, { MN.key, "Mongolian" },
            { MR.key, "Marathi" }, { MS.key, "Malay" }, { MT.key, "Maltese" }, { MY.key, "Burmese" },
            { MYV.key, "Erzya" }, { MZN.key, "Mazanderani" }, { NA.key, "Nauru" }, { NA.key, "Nauruan" },
            { NAH.key, "Nahuatl languages" }, { NAP.key, "Neapolitan" }, { NDS.key, "Low German" },
            { NDS.key, "Low Saxon" }, { NDS_NL.key, "Dutch Low Saxon" }, { NE.key, "Nepali" }, { NEW.key, "Newari" },
            { NG.key, "Ndonga" }, { NL.key, "Dutch" }, { NN.key, "Norwegian Nynorsk" },
            { NN.key, "Norwegian (Nynorsk)" }, { NO.key, "Norwegian" }, { NO.key, "Norwegian (Bokmål)" },
            { NOV.key, "Novial" }, { NRM.key, "Norman" }, { NV.key, "Navajo" }, { NY.key, "Nyanja" },
            { OC.key, "Occitan" }, { OM.key, "Oromo" }, { OR.key, "Oriya" }, { OS.key, "Ossetian" },
            { PA.key, "Panjabi" }, { PAG.key, "Pangasinan" }, { PAM.key, "Pampanga" }, { PAP.key, "Papiamento" },
            { PDC.key, "Pennsylvania German" }, { PI.key, "Pali" }, { PIH.key, "Pitcairn-Norfolk" },
            { PL.key, "Polish" }, { PMS.key, "Piemontese" }, { PS.key, "Pushto" }, { PS.key, "Pashto" },
            { PT.key, "Portuguese" }, { QU.key, "Quechua" }, { RM.key, "Romansh" }, { RM.key, "Raeto Romance" },
            { RMY.key, "Vlax Romani" }, { RN.key, "Rundi" }, { RN.key, "Kirundi" }, { RO.key, "Romanian" },
            { ROA_RUP.key, "Macedo Romanian" }, { ROA_RUP.key, "Aromanian" }, { ROA_TARA.key, "Tarantino" },
            { RU.key, "Russian" }, { RW.key, "Kinyarwanda" }, { RW.key, "Rwandi" }, { SA.key, "Sanskrit" },
            { SAH.key, "Yakut" }, { SC.key, "Sardinian" }, { SCN.key, "Sicilian" }, { SCO.key, "Scots" },
            { SD.key, "Sindhi" }, { SE.key, "Northern Sami" }, { SG.key, "Sango" }, { SH.key, "Serbo-Croatian" },
            { SI.key, "Sinhala" }, { SI.key, "Sinhalese" }, { SIMPLE.key, "Simple English" }, { SK.key, "Slovak" },
            { SL.key, "Slovenian" }, { SM.key, "Samoan" }, { SN.key, "Shona" }, { SO.key, "Somali" },
            { SQ.key, "Albanian" }, { SR.key, "Serbian" }, { SRN.key, "Sranan Tongo" }, { SS.key, "Swati" },
            { ST.key, "Southern Sotho" }, { STQ.key, "Saterfriesisch" }, { SU.key, "Sundanese" },
            { SV.key, "Swedish" }, { SW.key, "Swahili" }, { SZL.key, "Silesian" }, { TA.key, "Tamil" },
            { TE.key, "Telugu" }, { TET.key, "Tetum" }, { TG.key, "Tajik" }, { TH.key, "Thai" },
            { TI.key, "Tigrinya" }, { TK.key, "Turkmen" }, { TL.key, "Tagalog" }, { TN.key, "Tswana" },
            { TN.key, "Setswana" }, { TO.key, "Tonga (Tonga Islands)" }, { TO.key, "Tongan" },
            { TPI.key, "Tok Pisin" }, { TR.key, "Turkish" }, { TS.key, "Tsonga" }, { TT.key, "Tatar" },
            { TUM.key, "Tumbuka" }, { TW.key, "Twi" }, { TY.key, "Tahitian" }, { UDM.key, "Udmurt" },
            { UG.key, "Uighur" }, { UG.key, "Uyghur" }, { UK.key, "Ukrainian" }, { UR.key, "Urdu" },
            { UZ.key, "Uzbek" }, { VE.key, "Venda" }, { VEC.key, "Venetian" }, { VI.key, "Vietnamese" },
            { VLS.key, "Vlaams" }, { VO.key, "Volapük" }, { WA.key, "Walloon" }, { WAR.key, "Waray (Philippines)" },
            { WO.key, "Wolof" }, { WUU.key, "Wu" }, { XAL.key, "Kalmyk" }, { XH.key, "Xhosa" }, { XH.key, "Xhosan" },
            { YI.key, "Yiddish" }, { YO.key, "Yoruba" }, { ZA.key, "Zhuang" }, { ZEA.key, "Zeeuws" },
            { ZH.key, "Chinese" }, { ZH_CLASSICAL.key, "Classical Chinese" }, { ZH_MIN_NAN.key, "Min Nan" },
            { ZH_YUE.key, "Cantonese" }, { ZU.key, "Zulu" }, { MO.key, "Moldovan" }, { PNB.key, "Western Panjabi" }, };

    public static final String[] LANGUAGES_EN_ISO = new String[LNGS_EN.length];
    public static final String[] LANGUAGES_EN = new String[LNGS_EN.length];
    static {
        int i = 0;
        for (String[] lng : LNGS_EN) {
            LANGUAGES_EN_ISO[i] = lng[0];
            LANGUAGES_EN[i] = lng[1];
            i++;
        }
    }

    private static final String[][] LNGS_ORIGINAL = { { AA.key, "Afar" }, { AB.key, "Аҧсуа" }, { AF.key, "Afrikaans" },
            { AK.key, "Akan" }, { ALS.key, "Alemannisch" }, { AM.key, "አማርኛ" }, { AN.key, "Aragonés" },
            { ANG.key, "Anglo-Saxon" }, { AR.key, "العربية" }, { ARC.key, "ܐܪܡܝܐ" }, { AS.key, "অসমীয়া" },
            { AST.key, "Asturianu" }, { AV.key, "Авар" }, { AY.key, "Aymar" }, { AZ.key, "Azərbaycan" },
            { AZ.key, "آذربايجان ديلی" }, { BA.key, "Башҡорт" }, { BAR.key, "Boarisch" },
            { BAT_SMG.key, "Žemaitėška" }, { BCL.key, "Bikol Central" }, { BE.key, "Беларуская" },
            { BE_X_OLD.key, "Беларуская (тарашкевіца)" }, { BG.key, "Български" }, { BH.key, "भोजपुरी" },
            { BI.key, "Bislama" }, { BM.key, "Bamanankan" }, { BN.key, "বাংলা" }, { BO.key, "བོད་ཡིག" },
            { BPY.key, "ইমার ঠার" }, { BPY.key, "বিষ্ণুপ্রিয়া মণিপুরী" }, { BR.key, "Brezhoneg" },
            { BS.key, "Bosanski" }, { BUG.key, "ᨅᨔ ᨕᨘᨁᨗ" }, { BXR.key, "Буряад" }, { CA.key, "Català" },
            { CBK_ZAM.key, "Chavacano de Zamboanga" }, { CDO.key, "闽东话" }, { CDO.key, "Mìng-dĕ̤ng-ngṳ̄" },
            { CE.key, "Нохчийн" }, { CEB.key, "Cebuano" }, { CH.key, "Chamoru" }, { CHR.key, "ᏣᎳᎩ" },
            { CHY.key, "Tsetsêhestâhese" }, { CO.key, "Corsu" }, { CR.key, "Nēhiyawēwin" }, { CR.key, "ᓀᐦᐃᔭᐍᐏᐣ" },
            { CRH.key, "Qırımtatarca" }, { CS.key, "Česky" }, { CSB.key, "Kaszëbsczi" }, { CU.key, "Словѣ́ньскъ" },
            { CU.key, "ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ" }, { CV.key, "Чăвашла" }, { CY.key, "Cymraeg" }, { DA.key, "Dansk" },
            { DE.key, "Deutsch" }, { DIQ.key, "Zazaki" }, { DSB.key, "Dolnoserbski" }, { DV.key, "ދިވެހިބަސް" },
            { DZ.key, "ཇོང་ཁ" }, { EE.key, "Eʋegbe" }, { EL.key, "Ελληνικά" }, { EML.key, "Emiliàn e rumagnòl" },
            { EN.key, "English" }, { EO.key, "Esperanto" }, { ES.key, "Español" }, { ET.key, "Eesti" },
            { EU.key, "Euskara" }, { EXT.key, "Estremeñu" }, { FA.key, "فارسی" }, { FF.key, "Fulfulde" },
            { FI.key, "Suomi" }, { FIU_VRO.key, "Võro" }, { FJ.key, "Na Vosa Vakaviti" }, { FO.key, "Føroyskt" },
            { FR.key, "Français" }, { FRP.key, "Arpetan" }, { FUR.key, "Furlan" }, { FY.key, "Frysk" },
            { GA.key, "Gaeilge" }, { GAN.key, "赣语" }, { GD.key, "Gàidhlig" }, { GL.key, "Galego" },
            { GLK.key, "گیلکی" }, { GN.key, "Avañe'ẽ" }, { GOT.key, "𐌲𐌿𐍄𐌹𐍃𐌺" }, { GU.key, "ગુજરાતી" },
            { GV.key, "Gaelg" }, { HA.key, "هَوُسَ" }, { HAK.key, "Hak-kâ-fa" }, { HAW.key, "Hawai`i" },
            { HE.key, "עברית" }, { HI.key, "हिन्दी" }, { HIF.key, "Fiji Hindi" }, { HR.key, "Hrvatski" },
            { HSB.key, "Hornjoserbsce" }, { HT.key, "Kreyòl ayisyen" }, { HU.key, "Magyar" }, { HY.key, "Հայերեն" },
            { IA.key, "Interlingua" }, { ID.key, "Bahasa Indonesia" }, { IE.key, "Interlingue" }, { IG.key, "Igbo" },
            { IK.key, "Iñupiak" }, { ILO.key, "Ilokano" }, { IO.key, "Ido" }, { IS.key, "Íslenska" },
            { IT.key, "Italiano" }, { IU.key, "ᐃᓄᒃᑎᑐᑦ" }, { IU.key, "inuktitut" }, { JA.key, "日本语" },
            { JBO.key, "Lojban" }, { JV.key, "Basa Jawa" }, { KA.key, "ქართული" }, { KAA.key, "Qaraqalpaqsha" },
            { KAB.key, "Taqbaylit" }, { KG.key, "Kongo" }, { KI.key, "Gĩkũyũ" }, { KK.key, "Қазақша" },
            { KL.key, "Kalaallisut" }, { KM.key, "ភាសាខ្មែរ" }, { KN.key, "ಕನ್ನಡ" }, { KO.key, "한국어" },
            { KS.key, "कश्मीरी - (كشميري)" }, { KSH.key, "Ripoarisch" }, { KU.key, "Kurdî" }, { KU.key, "كوردی" },
            { KV.key, "Коми" }, { KW.key, "Kernewek" }, { KY.key, "Кыргызча" }, { LA.key, "Latina" },
            { LAD.key, "Ladino" }, { LB.key, "Lëtzebuergesch" }, { LBE.key, "Лакку" }, { LG.key, "Luganda" },
            { LI.key, "Limburgs" }, { LIJ.key, "Líguru" }, { LMO.key, "Lumbaart" }, { LN.key, "Lingála" },
            { LO.key, "ລາວ" }, { LT.key, "Lietuvių" }, { LV.key, "Latviešu" }, { MAP_BMS.key, "Basa Banyumasan" },
            { MDF.key, "Мокшень" }, { MG.key, "Malagasy" }, { MH.key, "Ebon" }, { MI.key, "Māori" },
            { MK.key, "Македонски" }, { ML.key, "മലയാളം" }, { MN.key, "Монгол" }, { MR.key, "मराठी" },
            { MS.key, "Bahasa Melayu" }, { MT.key, "Malti" }, { MY.key, "Myanmasa" }, { MYV.key, "Эрзянь" },
            { MZN.key, "مَزِروني" }, { NA.key, "Ekakairũ Naoero" }, { NAH.key, "Nahuatl" }, { NAP.key, "Nnapulitano" },
            { NDS.key, "Plattdüütsch" }, { NDS_NL.key, "Nedersaksisch" }, { NE.key, "नेपाली" },
            { NEW.key, "नेपाल भाषा" }, { NG.key, "Oshiwambo" }, { NL.key, "Nederlands" },
            { NN.key, "Norsk (nynorsk)" }, { NO.key, "Norsk (bokmål)" }, { NOV.key, "Novial" },
            { NRM.key, "Nouormand" }, { NRM.key, "Normaund" }, { NV.key, "Diné bizaad" }, { NY.key, "Chi-Chewa" },
            { OC.key, "Occitan" }, { OM.key, "Oromoo" }, { OR.key, "ଓଡ଼ିଆ" }, { OS.key, "Иронау" },
            { PA.key, "ਪੰਜਾਬੀ" }, { PAG.key, "Pangasinan" }, { PAM.key, "Kapampangan" }, { PAP.key, "Papiamentu" },
            { PDC.key, "Deitsch" }, { PI.key, "पािऴ" }, { PIH.key, "Norfuk" }, { PIH.key, "Pitkern" },
            { PL.key, "Polski" }, { PMS.key, "Piemontèis" }, { PS.key, "پښتو" }, { PT.key, "Português" },
            { QU.key, "Runa Simi" }, { RM.key, "Rumantsch" }, { RMY.key, "Romani" }, { RN.key, "Kirundi" },
            { RO.key, "Română" }, { ROA_RUP.key, "Armãneashce" }, { ROA_TARA.key, "Tarandíne" }, { RU.key, "Русский" },
            { RW.key, "Kinyarwanda" }, { SA.key, "संस्कृत" }, { SAH.key, "Саха тыла" }, { SC.key, "Sardu" },
            { SCN.key, "Sicilianu" }, { SCO.key, "Scots" }, { SD.key, "سنڌي" }, { SE.key, "Sámegiella" },
            { SG.key, "Sängö" }, { SH.key, "Srpskohrvatski" }, { SH.key, "Српскохрватски" }, { SI.key, "සිංහල" },
            { SIMPLE.key, "Simple English" }, { SK.key, "Slovenčina" }, { SL.key, "Slovenščina" },
            { SM.key, "Gagana Samoa" }, { SN.key, "chiShona" }, { SO.key, "Soomaaliga" }, { SQ.key, "Shqip" },
            { SR.key, "Српски" }, { SR.key, "Srpski" }, { SRN.key, "Sranantongo" }, { SS.key, "SiSwati" },
            { ST.key, "Sesotho" }, { STQ.key, "Seeltersk" }, { SU.key, "Basa Sunda" }, { SV.key, "Svenska" },
            { SW.key, "Kiswahili" }, { SZL.key, "Ślůnski" }, { TA.key, "தமிழ்" }, { TE.key, "తెలుగు" },
            { TET.key, "Tetun" }, { TG.key, "Тоҷикӣ" }, { TG.key, "tojikī" }, { TH.key, "ไทย" }, { TI.key, "ትግርኛ" },
            { TK.key, "Türkmen" }, { TL.key, "Tagalog" }, { TN.key, "Setswana" }, { TO.key, "faka-Tonga" },
            { TPI.key, "Tok Pisin" }, { TR.key, "Türkçe" }, { TS.key, "Xitsonga" }, { TT.key, "Tatarça" },
            { TT.key, "Татарча" }, { TUM.key, "chiTumbuka" }, { TW.key, "Twi" }, { TY.key, "Reo Mā`ohi" },
            { UDM.key, "Удмурт" }, { UG.key, "Uyghurche‎" }, { UG.key, "ئۇيغۇرچە" }, { UK.key, "Українська" },
            { UR.key, "اردو" }, { UZ.key, "O'zbek" }, { VE.key, "Tshivenda" }, { VEC.key, "Vèneto" },
            { VI.key, "Tiếng Việt" }, { VLS.key, "West-Vlams" }, { VO.key, "Volapük" }, { WA.key, "Walon" },
            { WAR.key, "Winaray" }, { WO.key, "Wolof" }, { WUU.key, "吴语" }, { XAL.key, "Хальмг" },
            { XH.key, "isiXhosa" }, { YI.key, "ייִדיש" }, { YO.key, "Yorùbá" }, { ZA.key, "Cuengh" },
            { ZEA.key, "Zeêuws" }, { ZH.key, "中文" }, { ZH_CLASSICAL.key, "文言" }, { ZH_MIN_NAN.key, "闽南话" },
            { ZH_MIN_NAN.key, "Bân-lâm-gú" }, { ZH_YUE.key, "粤语" }, { ZU.key, "isiZulu" }, { MO.key, "Moldoveana" },
            { PNB.key, "شاہ مکھی پنجابی (Shāhmukhī Pañj�" }, };

    public static final String[] LANGUAGES_ORIGINAL_ISO = new String[LNGS_ORIGINAL.length];
    public static final String[] LANGUAGES_ORIGINAL = new String[LNGS_ORIGINAL.length];
    static {
        int i = 0;
        for (String[] lng : LNGS_ORIGINAL) {
            LANGUAGES_ORIGINAL_ISO[i] = lng[0];
            LANGUAGES_ORIGINAL[i] = lng[1];
            i++;
        }
    }

}
